QuanLyThuVien/Controllers/QuanLyMuonTraSachController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuanLyThuVien.Data;
using QuanLyThuVien.Models;

namespace QuanLyThuVien.Controllers
{
    public class QuanLyMuonTraSachController : Controller
    {
        private readonly ApplicationDbContext _db;
        public QuanLyMuonTraSachController(ApplicationDbContext db)
        {
            _db = db;
        }

        // Mã tài khoản đăng nhập
        private int idDN = LoginController.id;

        // Get view sách đang mượn
        public IActionResult ViewSachMuon()
        {
            LinkedList<SachMuon> lstPhieuMuon = new LinkedList<SachMuon>();
            var dataPhieuMuons = from tt in _db.ThuThus
                                from pm in _db.PhieuMuons
                                from ctpm in _db.CTPhieuMuon
                                from dg in _db.DocGias
                                from s in _db.Saches
                                from ttv in _db.TheThuViens
                                where (pm.ID_PhieuMuon == ctpm.ID_PhieuMuon && pm.ID_The == ttv.ID_The
                                      && pm.ID_ThuThu == tt.ID_ThuThu && ttv.ID_The == dg.ID_The 
                                      && ctpm.ID_Sach == s.ID_Sach && ctpm.TrangThai == 0)
                                select new
                                {
                                    MaPM = pm.ID_PhieuMuon,
                                    TenNguoiTao = tt.TenThuThu,
                                    MaTheTV = ttv.ID_The,
                                    TenDg = dg.TenDocGia,
                                    MaSach = s.ID_Sach,
                                    TenSach = s.TenSach,
                                    SoLuongMuon = ctpm.SoLuongMuon,
                                    NgayTaoPM = pm.NgayTaoPhieu,
                                    NgayHenTra = pm.NgayHenTra,
                                    GhiChuMuon = pm.GhiChuMuon
                                };

            foreach(var data in dataPhieuMuons)
            {
                SachMuon obj = new SachMuon(data.MaPM, data.TenNguoiTao, data.MaTheTV, data.TenDg, data.MaSach, 
                    data.TenSach, data.SoLuongMuon, data.NgayTaoPM, data.NgayHenTra, data.GhiChuMuon);
                lstPhieuMuon.AddLast(obj);
            }

            return View(lstPhieuMuon);
        }

        // Get view lập phiếu mượn
        public IActionResult CreatePhieuMuon()
        {
            return View();
        }

        // Post lập phiếu mượn
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SachMuon model)
        {
            // Kiểm tra mã thẻ thư viện, mã sách có tồn tại không
            var theThuVien = _db.TheThuViens.Find(model.MaTheThuVien);
            var sach = _db.Saches.Find(model.MaSach);
            // True nếu số lượng sách mượn lớn hơn số lượng sách tồn kho
            bool isSoLuongSach = sach.SoLuong - model.SoLuongMuon < 0 ? true : false;

            if (theThuVien == null)
                ModelState.AddModelError("MaTheThuVien", "Mã thẻ thư viện không tồn tại!");
            if (sach == null)
                ModelState.AddModelError("MaSach", "Mã sách không tồn tại!");
            if (model.SoLuongMuon <= 0)
                ModelState.AddModelError("SoLuongMuon", "Số lượng mượn phải lớn hơn 0");
             if (isSoLuongSach)
                ModelState.AddModelError("SoLuongMuon", "Số lượng sách trong kho không đủ!");

            if (theThuVien != null && sach != null && !isSoLuongSach && model.SoLuongMuon > 0)
            {
                try
                {
                    // Lấy mã thủ thư
                    var thuthu = from tt in _db.ThuThus
                                 where tt.ID_TaiKhoan == idDN
                                 select tt;
                    int maThuThu = 0;
                    foreach (var tt in thuthu)
                    {
                        maThuThu = tt.ID_ThuThu;
                    }

                    // Thêm dữ liệu vào bảng phiếu mượn
                    PhieuMuon pm = new PhieuMuon();
                    pm.NgayTaoPhieu = model.NgayTaoPhieu;
                    pm.NgayHenTra = model.NgayHenTra;
                    pm.ID_ThuThu = maThuThu;
                    pm.ID_The = model.MaTheThuVien;
                    if (string.IsNullOrEmpty(model.GhiChuMuon))
                        pm.GhiChuMuon = "Trống";
                    else
                        pm.GhiChuMuon = model.GhiChuMuon;

                    await _db.PhieuMuons.AddAsync(pm);
                    await _db.SaveChangesAsync();

                    // Thêm dữ liệu vào bảng chi tiết phiếu mượn
                    CTPhieuMuon ctpm = new CTPhieuMuon();
                    // Lấy mã phiếu mượn vừa thêm vào cơ sở dữ liệu
                    int maPM = _db.PhieuMuons.Max(id => id.ID_PhieuMuon);
                    ctpm.ID_PhieuMuon = maPM;
                    ctpm.ID_Sach = model.MaSach;
                    ctpm.GhiChuTra = "Trống";
                    // Trạng thái: 0 -> đang mượn, 1 -> đã trả
                    ctpm.TrangThai = 0;
                    ctpm.SoLuongMuon = model.SoLuongMuon;
                    await _db.CTPhieuMuon.AddAsync(ctpm);
                    await _db.SaveChangesAsync();

                    // Sửa lại số lượng sách khi lập phiếu mượn
                    UpdateSach(model.MaSach, model.SoLuongMuon);

                    TempData["success"] = "Lập phiếu mượn thành công";
                    return RedirectToAction("ViewSachMuon");
                } catch(Exception ex)
                {
                    TempData["error"] = ex.InnerException.Message;
                    return View("CreatePhieuMuon", model);
                }

            }
            return View("CreatePhieuMuon", model);
        }

        // Phương thức cập nhật số lượng sách khi tạo phiếu mượn
        public async Task UpdateSach(int maSach, int soLuongMuon)
        {
            var sachObj = _db.Saches.Find(maSach);
            int soLuongNew = sachObj.SoLuong - soLuongMuon;
            if(sachObj != null)
            {
                sachObj.SoLuong = soLuongNew;
                _db.Saches.Update(sachObj);
                await _db.SaveChangesAsync();
            }
        }

        // Phương thức cập nhật số lượng sách khi sửa phiếu mượn
        public async Task UpdateSach(int maSach, int soLuongOld, int soLuongNew)
        {
            var sachObj = _db.Saches.Find(maSach);
            int soLuong = sachObj.SoLuong - soLuongNew + soLuongOld;
            if (sachObj != null)
            {
                sachObj.SoLuong = soLuong;
                _db.Saches.Update(sachObj);
                await _db.SaveChangesAsync();
            }
        }

        // Phương thức cập nhật số lượng sách khi xóa phiếu mượn
        public async Task UpdateSachWhenDelete(int maSach, int soLuongMuon)
        {
            Sach? s = _db.Saches.Find(maSach);
            int soLuongNew = s.SoLuong + soLuongMuon;
            if (s != null)
            {
                s.SoLuong = soLuongNew;
                _db.Saches.Update(s);
                await _db.SaveChangesAsync();
            }
        }

        // Get view edit 
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var data = from tt in _db.ThuThus
                      from pm in _db.PhieuMuons
                      from ctpm in _db.CTPhieuMuon
                      from dg in _db.DocGias
                      from s in _db.Saches
                      from ttv in _db.TheThuViens
                      where (pm.ID_PhieuMuon == ctpm.ID_PhieuMuon && pm.ID_The == ttv.ID_The
                            && pm.ID_ThuThu == tt.ID_ThuThu && ttv.ID_The == dg.ID_The
                            && ctpm.ID_Sach == s.ID_Sach && pm.ID_PhieuMuon == id)
                      select new
                      {
                          MaPM = pm.ID_PhieuMuon,
                          TenNguoiTao = tt.TenThuThu,
                          MaTheTV = ttv.ID_The,
                          TenDg = dg.TenDocGia,
                          MaSach = s.ID_Sach,
                          TenSach = s.TenSach,
                          SoLuongMuon = ctpm.SoLuongMuon,
                          NgayTaoPM = pm.NgayTaoPhieu,
                          NgayHenTra = pm.NgayHenTra,
                          GhiChuMuon = pm.GhiChuMuon
                      };

            SachMuon? obj = new SachMuon();
            foreach(var i in data)
            {
                obj = new SachMuon(i.MaPM, i.TenNguoiTao, i.MaTheTV, i.TenDg, i.MaSach,
                    i.TenSach, i.SoLuongMuon, i.NgayTaoPM, i.NgayHenTra, i.GhiChuMuon);
            }

            if (obj == null)
                return NotFound();

            return View(obj);
        }

        // Post edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SachMuon model)
        {
            // Lấy số sách mượn của bảng CTPhieuMuon khi chưa sửa chi tiết phiếu mượn
            var CTPhieuMuon = from ctpm in _db.CTPhieuMuon
                             where ctpm.ID_PhieuMuon == model.MaPhieuMuon
                             select ctpm.SoLuongMuon;
            int soLuongOld = 0;
            foreach(var data in CTPhieuMuon)
            {
                soLuongOld = data;
                break;
            }

            // Kiểm tra mã thẻ thư viện, mã sách có tồn tại không
            var theThuVien = _db.TheThuViens.Find(model.MaTheThuVien);
            var sach = _db.Saches.Find(model.MaSach);
            // True nếu số lượng sách mượn lớn hơn số lượng sách tồn kho
            bool isSoLuongSach = sach.SoLuong - model.SoLuongMuon + soLuongOld < 0 ? true : false;

            if (theThuVien == null)

QuanLyThuVien/Views/QuanLyMuonTraSach/CreatePhieuMuon.cshtml
@model SachMuon
@{
    ViewData["Title"] = "Lập phiếu mượn";
}

<main>
    <form method="post" asp-controller="QuanLyMuonTraSach" asp-action="Create" style="width:50%;">
        <fieldset>
            <legend>Lập phiếu mượn</legend>
            <div class="form-group d-flex align-items-end">
                <div style="flex:auto; margin-right: 12px;">
                    <label asp-for="MaTheThuVien" class="form-label mt-4">Mã thẻ thư viện <span class="text-danger">*</span></label>
                    <input asp-for="MaTheThuVien" type="text" class="form-control flex" required placeholder="Nhập mã thẻ thư viện">
                    <span asp-validation-for="MaTheThuVien" class="text-danger"></span>
                </div>
                <div style="flex:auto;">
                    <label asp-for="MaSach" class="form-label mt-4">Mã sách <span class="text-danger">*</span></label>
                    <input asp-for="MaSach" type="text" name="maSach" class="form-control" required placeholder="Nhập mã sách">
                    <span asp-validation-for="MaSach" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group d-flex align-items-end">
                <div style="flex:auto; margin-right: 12px;">
                    <label asp-for="NgayTaoPhieu" class="form-label mt-4">Ngày mượn <span class="text-danger">*</span></label>
                    <input asp-for="NgayTaoPhieu" type="date" class="form-control" required />
                </div>
                <div style="flex:auto;">
                    <label asp-for="NgayHenTra" class="form-label mt-4">Ngày hẹn trả <span class="text-danger">*</span></label>
                    <input asp-for="NgayHenTra" type="date" class="form-control" required />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="SoLuongMuon" class="form-label mt-4">Số lượng mượn</label>
                <input asp-for="SoLuongMuon" type="number" class="form-control" required placeholder="Nhập số lượng mượn" />
                <span asp-validation-for="SoLuongMuon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GhiChuMuon" class="form-label mt-4">Ghi chú</label>
                <input asp-for="GhiChuMuon" type="text" class="form-control" placeholder="Nhập ghi chú mượn" />
            </div>
        </fieldset>
        
        <fieldset style="position:absolute; bottom:20px;">
            <a asp-controller="QuanLyMuonTraSach" asp-action="ViewSachMuon" class="btn btn-outline-primary" style="margin-right: 4px">Quay lại</a>
            <button type="submit" class="btn btn-success">
                <i class="bi bi-plus-circle"></i>&nbsp; Lưu
            </button>
        </fieldset>
    </form>
</main>

QuanLyThuVien/Views/QuanLyMuonTraSach/Delete.cshtml
@model SachMuon
@{
    ViewData["Title"] = "Delete";
}

<main>
    <form method="post" asp-controller="QuanLyMuonTraSach" asp-action="DeletePost" id="form-delete" style="width:50%;">
        <fieldset>
            <legend>Xóa phiếu mượn</legend>
            <div class="form-grop">
                <input asp-for="MaPhieuMuon" type="text" class="form-control" name="maPhieuMuon" hidden>
            </div>
            <div class="form-group d-flex align-items-end">
                <div style="flex:auto; margin-right: 12px;">
                    <label asp-for="MaTheThuVien" class="form-label mt-4">Mã thẻ thư viện <span class="text-danger">*</span></label>
                    <input asp-for="MaTheThuVien" type="text" class="form-control" disabled="" />
                </div>
                <div style="flex:auto;">
                    <label asp-for="MaSach" class="form-label mt-4">Mã sách <span class="text-danger">*</span></label>
                    <input asp-for="MaSach" type="text" name="maSach" class="form-control" disabled="" />
                </div>
            </div>
            <div class="form-group d-flex align-items-end">
                <div style="flex:auto; margin-right: 12px;">
                    <label asp-for="NgayTaoPhieu" class="form-label mt-4">Ngày mượn <span class="text-danger">*</span></label>
                    <input asp-for="NgayTaoPhieu" type="date" class="form-control" disabled="" />
                </div>
                <div style="flex:auto;">
                    <label asp-for="NgayHenTra" class="form-label mt-4">Ngày hẹn trả <span class="text-danger">*</span></label>
                    <input asp-for="NgayHenTra" type="date" class="form-control" disabled="" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="SoLuongMuon" class="form-label mt-4">Số lượng mượn</label>
                <input asp-for="SoLuongMuon" type="number" class="form-control" disabled="" />
            </div>
            <div class="form-group">
                <label asp-for="GhiChuMuon" class="form-label mt-4">Ghi chú</label>
                <input asp-for="GhiChuMuon" type="text" class="form-control" disabled="" />
            </div>
        </fieldset>

        <fieldset style="position:absolute; bottom:0;">
            <a asp-controller="QuanLyMuonTraSach" asp-action="ViewSachMuon" class="btn btn-outline-primary" style="margin-right: 4px">Quay lại</a>
            <button type="button" class="btn btn-danger" onclick="handleSubmitForm()">Delete</button>
        </fieldset>
    </form>

    <div class="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Thông báo</h5>
                    <button type="button" class="btn-close" value="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Bạn có chắc chắn muốn xóa?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" value="submit" class="btn btn-danger">Yes</button>
                    <button type="button" class="btn btn-secondary" value="close" data-bs-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
</main>

QuanLyThuVien/Views/QuanLyMuonTraSach/Edit.cshtml
@model SachMuon
@{
    ViewData["Title"] = "Edit";
}

<main>
    <form method="post" asp-controller="QuanLyMuonTraSach" asp-action="Edit" style="width:50%;">
        <fieldset>
            <legend>Chỉnh sửa phiếu mượn</legend>
            <div class="form-group">
                <label asp-for="MaPhieuMuon" class="form-label mt-4">Mã phiếu mượn</label>
                <input asp-for="MaPhieuMuon" type="text" readonly class="form-control" />
            </div>
            <div class="form-group d-flex align-items-end">
                <div style="flex:auto; margin-right: 12px;">
                    <label asp-for="MaTheThuVien" class="form-label mt-4">Mã thẻ thư viện <span class="text-danger">*</span></label>
                    <input asp-for="MaTheThuVien" type="text" class="form-control" required placeholder="Nhập mã thẻ thư viện">
                    <span asp-validation-for="MaTheThuVien" class="text-danger"></span>
                </div>
                <div style="flex:auto;">
                    <label asp-for="MaSach" class="form-label mt-4">Mã sách <span class="text-danger">*</span></label>
                    <input asp-for="MaSach" type="text" name="maSach" class="form-control" required placeholder="Nhập mã sách">
                    <span asp-validation-for="MaSach" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group d-flex align-items-end">
                <div style="flex:auto; margin-right: 12px;">
                    <label asp-for="NgayTaoPhieu" class="form-label mt-4">Ngày mượn <span class="text-danger">*</span></label>
                    <input asp-for="NgayTaoPhieu" type="date" class="form-control" required />
                </div>
                <div style="flex:auto;">
                    <label asp-for="NgayHenTra" class="form-label mt-4">Ngày hẹn trả <span class="text-danger">*</span></label>
                    <input asp-for="NgayHenTra" type="date" class="form-control" required />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="SoLuongMuon" class="form-label mt-4">Số lượng mượn</label>
                <input asp-for="SoLuongMuon" type="number" class="form-control" required placeholder="Nhập số lượng mượn" />
                <span asp-validation-for="SoLuongMuon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GhiChuMuon" class="form-label mt-4">Ghi chú</label>
                <input asp-for="GhiChuMuon" type="text" class="form-control" placeholder="Nhập ghi chú mượn" />
            </div>
        </fieldset>

        <fieldset style="position:absolute; bottom:0;">
            <a asp-controller="QuanLyMuonTraSach" asp-action="ViewSachMuon" class="btn btn-outline-primary" style="margin-right: 4px">Quay lại</a>
            <button type="submit" class="btn btn-success">Update</button>
        </fieldset>
    </form>
</main>

QuanLyThuVien/Views/QuanLyMuonTraSach/ViewSachMuon.cshtml
@model LinkedList<SachMuon>

@{
    ViewData["Title"] = "Phiếu mượn";
}

<main class="pt-2">
    <div>
        <div class="text-start d-flex" style="margin: 12px 0;">
            <a asp-controller="QuanLyMuonTraSach" asp-action="ViewSachMuon" class="btn btn-outline-primary @(Context.Request.Path == "/QuanLyMuonTraSach/ViewSachMuon" ? "active" : "")" style="border-top-right-radius: 0; border-bottom-right-radius: 0;">
                Phiếu đang mượn
            </a>
            <a asp-controller="QuanLyMuonTraSach" asp-action="ViewSachTra" class="btn btn-outline-primary @(Context.Request.Path == "/QuanLyMuonTraSach/ViewSachTra" ? "active" : "")" style="border-top-left-radius: 0; border-bottom-left-radius: 0;">
                Phiếu đã trả
            </a>
        </div>
        <div class="text-end">
            <a asp-controller="QuanLyMuonTraSach" asp-action="CreatePhieuMuon" class="btn btn-success" style="border-top-right-radius: 0; border-bottom-right-radius: 0;">
                Lập phiếu mượn
            </a>
        </div>
        <hr />
        <table class="table table-hover">
            <thead>
                <tr class="table-primary">
                    <th scope="col">Số phiếu</th>
                    <th scope="col">Người tạo phiếu</th>
                    <th scope="col">Tên độc giả</th>
                    <th scope="col">Tên sách</th>
                    <th scope="col">Số lượng mượn</th>
                    <th scope="col">Ngày tạo phiếu</th>
                    <th scope="col">Ngày hẹn trả</th>
                    <th scope="col">Ghi chú mượn</th>
                    <th scope="col">Hành động</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.MaPhieuMuon</th>
                        <td>@item.TenNguoiTao</td>
                        <td>@item.TenDocGia</td>
                        <td>@item.TenSach</td>
                        <td>@item.SoLuongMuon</td>
                        <td>@item.NgayTaoPhieu</td>
                        <td>@item.NgayHenTra</td>
                        <td>@item.GhiChuMuon</td>
                        <td>
                            <a asp-controller="QuanLyMuonTraSach" asp-action="Edit" asp-route-id="@item.MaPhieuMuon" class="btn btn-outline-primary" title="Sửa">
                                <i class="bi bi-gear"></i>
                            </a>
                            <a asp-controller="QuanLyMuonTraSach" asp-action="Delete" asp-route-id="@item.MaPhieuMuon" class="btn btn-outline-danger" style="margin: 0 8px;" title="Xóa">
                                <i class="bi bi-trash3"></i>
                            </a>
                            <a asp-controller="QuanLyMuonTraSach" asp-action="TraSach" asp-route-id="@item.MaPhieuMuon" class="btn btn-outline-success">
                                <span>Trả sách</span>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</main>

QuanLyThuVien/Views/QuanLyMuonTraSach/ViewSachTra.cshtml
@model LinkedList<SachTra>
@{
    ViewData["Title"] = "ViewSachTra";
}

<main>
    <div>
        <div class="text-start d-flex" style="margin: 12px 0;">
            <a asp-controller="QuanLyMuonTraSach" asp-action="ViewSachMuon" class="btn btn-outline-primary @(Context.Request.Path == "/QuanLyMuonTraSach/ViewSachMuon" ? "active" : "")" style="border-top-right-radius: 0; border-bottom-right-radius: 0;">
                Phiếu đang mượn
            </a>
            <a asp-controller="QuanLyMuonTraSach" asp-action="ViewSachTra" class="btn btn-outline-primary @(Context.Request.Path == "/QuanLyMuonTraSach/ViewSachTra" ? "active" : "")" style="border-top-left-radius: 0; border-bottom-left-radius: 0;">
                Phiếu đã trả
            </a>
        </div>
        <hr />
        <table class="table table-hover">
            <thead>
                <tr class="table-primary">
                    <th scope="col">Số phiếu</th>
                    <th scope="col">Mã sách</th>
                    <th scope="col">Tên sách</th>
                    <th scope="col">Mã thẻ thư viện</th>
                    <th scope="col">Tên độc giả</th>
                    <th scope="col">Số lượng mượn</th>
                    <th scope="col">Ngày trả</th>
                    <th scope="col">Ghi chú trả</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.Id_PhieuMuon</th>
                        <td>@item.Id_Sach</td>
                        <td>@item.TenSach</td>
                        <td>@item.Id_MaThe</td>
                        <td>@item.TenDocGia</td>
                        <td>@item.SlMuon</td>
                        <td>@item.NgayTra</td>
                        <td>@item.GhiChuTra</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</main>