QuanLyThuVien/Controllers/QuanTriHeThongController.cs
using Microsoft.AspNetCore.Mvc;
using QuanLyThuVien.Data;
using QuanLyThuVien.Models;

namespace QuanLyThuVien.Controllers
{
    public class QuanTriHeThongController : Controller
    {
        private readonly ApplicationDbContext _db;
        private string vaiTro = LoginController.layout.VaiTro;
        public QuanTriHeThongController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET
        public IActionResult Index()
        {
            if(vaiTro == "Admin")
            {
                IQueryable<TaiKhoan> dataTaiKhoan = getDataTaiKhoan();
                if (dataTaiKhoan.Count() <= 0)
                {
                    TempData["message"] = "Dữ liệu trống";
                }
                return View(dataTaiKhoan);
            }
            TempData["message"] = "Bạn không có quyền truy cập vào chức năng này!!!";
            return RedirectToAction("Index", "Home");
        }

        // GET
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TaiKhoan obj, string confirmPassword)
        {
            string pass = obj.MatKhau;
            string confirm = confirmPassword;

            if(pass != confirm)
            {
                ModelState.AddModelError("MatKhau", "Mật khẩu xác nhận không đúng");
            } else
            {
                try
                {
                    _db.TaiKhoans.Add(obj);
                    await _db.SaveChangesAsync();
                    TempData["success"] = "Thêm tài khoản thành công";
                    return RedirectToAction("Index");
                } catch (Exception ex)
                {
                    TempData["error"] = ex.InnerException.Message;
                    return View(obj);
                }
            }

            return View(obj);
        }

        // GET
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var taiKhoanFromDb = _db.TaiKhoans.Find(id);
            if(taiKhoanFromDb == null) { return NotFound(); }
            return View(taiKhoanFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TaiKhoan obj, string confirmPassword)
        {
            string pass = obj.MatKhau;
            string confirm = confirmPassword;
            if (pass != confirm)
            {
                ModelState.AddModelError("MatKhau", "Mật khẩu xác nhận không đúng");
            }
            else
            {
                try
                {
                    _db.TaiKhoans.UpdateRange(obj);
                    await _db.SaveChangesAsync();
                    TempData["success"] = "Sửa thông tin tài khoản thành công";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.InnerException.Message;
                    return View(obj);
                }
            }

            return View(obj);
        }

        // GET
        public IActionResult Delete(int? id) 
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var taiKhoanFromDb = _db.TaiKhoans.Find(id);
            if (taiKhoanFromDb == null) { return NotFound(); }
            return View(taiKhoanFromDb);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int? id_taikhoan)
        {
            var obj = _db.TaiKhoans.Find(id_taikhoan);
            try
            {
                if (obj == null) { return NotFound(); }
                _db.TaiKhoans.Remove(obj);
                await _db.SaveChangesAsync();
                TempData["success"] = "Xóa thông tin tài khoản thành công";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.InnerException.Message;
                return View(obj);
            }
        }


        // Method get data table TaiKhoan
        public IQueryable<TaiKhoan> getDataTaiKhoan()
        {
            var obj = from tk in _db.TaiKhoans
                      where tk.VaiTro != "Admin"
                      select tk;
            return obj;
        }
    }
}

QuanLyThuVien/Views/QuanTriHeThong/Create.cshtml
@model TaiKhoan
@{
    ViewData["Title"] = "Create";
}

<main>
    <form method="post" style="width: 50%;">
        <fieldset>
            <legend>Tạo mới tài khoản</legend>
            <div class="form-group">
                <label asp-for="TenDangNhap" class="form-label mt-4">Tên tài khoản</label>
                <input asp-for="TenDangNhap" type="text" class="form-control" id="TenDangNhap" placeholder="Nhập tên tài khoản">
                <span asp-validation-for="TenDangNhap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatKhau" class="form-label mt-4">Mật khẩu</label>
                <input asp-for=MatKhau type="password" class="form-control" id="MatKhau" placeholder="Nhập mật khẩu" autocomplete="off">
                <span asp-validation-for="MatKhau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="ConfirmInputPassword" class="form-label mt-4">Xác nhận mật khẩu</label>
                <input type="password" required class="form-control" id="ConfirmInputPassword" name="confirmPassword" placeholder="Nhập lại mật khẩu" autocomplete="off">
            </div>
            <div class="form-group">
                <label asp-for="VaiTro" class="form-label mt-4">Chọn vai trò</label>
                <select class="form-select" id="VaiTro" asp-for="VaiTro">
                    <option>Admin</option>
                    <option>Thủ thư</option>
                    <option>Độc giả</option>
                </select>
            </div>
            <div class="mt-3">
                <a asp-controller="QuanTriHeThong" asp-action="Index" class="btn btn-outline-primary" style="margin-right: 4px">Quay lại</a>
                <button type="submit" class="btn btn-success">
                    <i class="bi bi-plus-circle"></i>&nbsp; Create
                </button>
            </div>
        </fieldset>
    </form>
</main>

QuanLyThuVien/Views/QuanTriHeThong/Delete.cshtml
@model TaiKhoan
@{
    ViewData["Title"] = "Delete";
}

<main>
    <form method="post" asp-action="DeletePost" style="width: 50%;" id="form-delete">
        <fieldset>
            <legend>Xóa thông tin</legend>
            <div class="form-group">
                <label asp-for="ID_TaiKhoan" class="form-label mt-4">Id tài khoản</label>
                <input asp-for="ID_TaiKhoan" class="form-control" id="ID_TaiKhoan" type="text" readonly>
            </div>
            <div class="form-group">
                <label asp-for="TenDangNhap" class="form-label mt-4">Tên tài khoản</label>
                <input asp-for="TenDangNhap" type="text" class="form-control" id="TenDangNhap" placeholder="Tên tài khoản" readonly>
            </div>
            <div class="form-group">
                <label asp-for="MatKhau" class="form-label mt-4">Mật khẩu</label>
                <input asp-for=MatKhau type="text" class="form-control" id="MatKhau" placeholder="Mật khẩu" readonly>
            </div>
            <div class="form-group">
                <label asp-for="VaiTro" class="form-label mt-4">Chọn vai trò</label>
                <select class="form-select" id="VaiTro" asp-for="VaiTro" disabled>
                    <option>Admin</option>
                    <option>Thủ thư</option>
                    <option>Độc giả</option>
                </select>
            </div>
            <div class="mt-3">
                <a asp-controller="QuanTriHeThong" asp-action="Index" class="btn btn-outline-primary" style="margin-right: 4px">Quay lại</a>
                <button type="button" class="btn btn-danger" onclick="handleSubmitForm()">Delete</button>
            </div>
        </fieldset>
    </form>
    <div class="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Thông báo</h5>
                    <button type="button" class="btn-close" value="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Bạn có chắc chắn muốn xóa?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" value="submit" class="btn btn-danger">Yes</button>
                    <button type="button" class="btn btn-secondary" value="close" data-bs-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
</main>

QuanLyThuVien/Views/QuanTriHeThong/Edit.cshtml
@model TaiKhoan
@{
    ViewData["Title"] = "Edit";
}

<main>
    <form method="post" asp-action="Edit" style="width: 50%;">
        <fieldset>
            <legend>Cập nhật thông tin</legend>
            <div class="form-group">
                <label asp-for="ID_TaiKhoan" class="form-label mt-4">Id tài khoản</label>
                <input asp-for="ID_TaiKhoan" class="form-control" id="ID_TaiKhoan" type="text" readonly>
            </div>
            <div class="form-group">
                <label asp-for="TenDangNhap" class="form-label mt-4">Tên tài khoản</label>
                <input asp-for="TenDangNhap" type="text" class="form-control" id="TenDangNhap" placeholder="Nhập tên tài khoản">
                <span asp-validation-for="TenDangNhap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatKhau" class="form-label mt-4">Mật khẩu</label>
                <input asp-for=MatKhau type="password" class="form-control" id="MatKhau" placeholder="Nhập mật khẩu" autocomplete="off">
                <span asp-validation-for="MatKhau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="ConfirmInputPassword" class="form-label mt-4">Xác nhận mật khẩu</label>
                <input type="password" required class="form-control" id="ConfirmInputPassword" name="confirmPassword" placeholder="Nhập lại mật khẩu" autocomplete="off">
            </div>
            <div class="form-group">
                <label asp-for="VaiTro" class="form-label mt-4">Chọn vai trò</label>
                <select class="form-select" id="VaiTro" asp-for="VaiTro">
                    <option>Admin</option>
                    <option>Thủ thư</option>
                    <option>Độc giả</option>
                </select>
            </div>
            <div class="mt-3">
                <a asp-controller="QuanTriHeThong" asp-action="Index" class="btn btn-outline-primary" style="margin-right: 4px">Quay lại</a>
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </fieldset>
    </form>
</main>

QuanLyThuVien/Views/QuanTriHeThong/Index.cshtml
@model IQueryable<TaiKhoan>
@{
    ViewData["Title"] = "Phan quyen";
}

<main>
    <h2 class="lv2">Danh sách tài khoản trong hệ thống</h2>
    <div class="text-start" style="margin: 12px 0;">
        <a asp-controller="QuanTriHeThong" asp-action="Create" class="btn btn-outline-primary">
            <i class="bi bi-plus-circle"></i>&nbsp; Tạo mới
        </a>
    </div>
    <table class="table table-hover">
        <thead>
            <tr class="table-primary">
                <th scope="col">Id</th>
                <th scope="col">Tên đăng nhập</th>
                <th scope="col">Mật khẩu</th>
                <th scope="col">Vai trò</th>
                <th scope="col">Hành động</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.ID_TaiKhoan</th>
                    <td>@item.TenDangNhap</td>
                    <td>@item.MatKhau</td>
                    <td>@item.VaiTro</td>
                    <td>
                        <a asp-controller="QuanTriHeThong" asp-action="Edit" asp-route-id="@item.ID_TaiKhoan" class="btn btn-outline-primary" style="margin-right: 8px" title="Sửa">
                            <i class="bi bi-gear"></i>
                        </a>
                        <a asp-controller="QuanTriHeThong" asp-action="Delete" asp-route-id="@item.ID_TaiKhoan" class="btn btn-outline-danger" title="Xóa">
                            <i class="bi bi-trash3"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</main>