QuanLyThuVien/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using QuanLyThuVien.Data;
using QuanLyThuVien.Models;

namespace QuanLyThuVien.Controllers
{
    public class LoginController : Controller
    {
        private readonly ApplicationDbContext _db;
        public LoginController(ApplicationDbContext db)
        {
            _db = db;
        }

        public static int id;
        // Model lưu thông tin tên đăng nhập, vai trò dùng chuyển dữ liệu qua _Layout.cshtml
        public static LayoutModel layout;

        public IActionResult Index()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(string taikhoan, string matkhau)
        {
            string username = taikhoan;
            string password = matkhau;
            // Truy van linq kiem tra tai khoan dang nhap
            var obj = from tk in _db.TaiKhoans
                      where (tk.TenDangNhap == username && tk.MatKhau == password)
                      select tk;
            foreach (var taiKhoan in obj)
            {
                if (taiKhoan.VaiTro == "Admin" || taiKhoan.VaiTro == "Thủ thư")
                {
                    id = taiKhoan.ID_TaiKhoan;

                    layout = new LayoutModel(taiKhoan.TenDangNhap, taiKhoan.VaiTro);
                    return RedirectToAction("Index", "Home");

                    /*return RedirectToRoute(new
                    {
                        Controller = "Home",
                        Action = "Index"
                    });*/

                    /*return View("Views/Home/Index.cshtml", id);*/
                } else
                {
                    TempData["message"] = "Bạn không có quyền truy cập vào hệ thống!!!";
                    return View("Index");
                }
            }
            TempData["error"] = "Tài khoản hoặc mật khẩu không chính xác!!!";
            return View("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Logout()
        {
            return View("Index");
        }
    }
}

QuanLyThuVien/Controllers/QuanLySachController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Diagnostics;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Design.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using QuanLyThuVien.Data;
using QuanLyThuVien.Models;

namespace QuanLyThuVien.Controllers
{
    public class QuanLySachController : Controller
    {
        private readonly ApplicationDbContext _db;
        public QuanLySachController(ApplicationDbContext db)
        {
            _db = db;
        }

        public List<SelectListItem> TheLoaiSelectList = new List<SelectListItem>();

        // GET View Index
        public IActionResult Index()
        {
            LinkedList<InfoBook> lstSach = getDataSach();
            if(lstSach.Count <= 0)
            {
                TempData["message"] = "Dữ liệu trống";
                return View(lstSach);
            }
            return View(lstSach);
        }

        // Post search sách
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SearchSach(string? searchInput)
        {
            // Danh sách lưu thông tin để hiện thị ra view
            LinkedList<InfoBook> lstSach = new LinkedList<InfoBook>();

            // Truy vấn lấy dữ liệu thông tin sách
            var dataSach = from s in _db.Saches
                           from tg in _db.TacGias
                           from tl in _db.TheLoais
                           where (s.ID_TacGia == tg.ID_TacGia && s.ID_TheLoai == tl.ID_TheLoai)
                           select new
                           {
                               sach = new Sach(s.ID_Sach, s.TenSach, s.GiaTien, s.SoLuong, s.UrlImg, s.NgayNhap),
                               tacGia = new TacGia(tg.ID_TacGia, tg.TenTacGia, tg.QuocGia),
                               theLoai = new TheLoai(tl.ID_TheLoai, tl.TenTheLoai)
                           };
            foreach (var item in dataSach)
            {
                // Nếu khớp với từ tìm kiếm thì thêm vào danh sách lstSach
                var isSearch = item.sach.ID_Sach.ToString() == searchInput
                                || item.sach.TenSach.ToUpper().Contains(searchInput.ToUpper());
                if(isSearch)
                {
                    InfoBook info = new InfoBook(item.sach, item.tacGia, item.theLoai);
                    lstSach.AddLast(info);
                }
            }

            if (lstSach.Count <= 0)
            {
                TempData["message"] = "Không tìm thấy thông tin sách";
                return View("Index", lstSach);
            }

            TempData["message"] = $"Tìm thấy {lstSach.Count()} kết quả";
            return View("Index", lstSach);
        }

        // Method get data thông tin sách để hiển thị lên trang Index
        public LinkedList<InfoBook> getDataSach()
        {
            LinkedList<InfoBook> lstSach = new LinkedList<InfoBook>();
            var dataSach = from s in _db.Saches
                           from tg in _db.TacGias
                           from tl in _db.TheLoais
                           where (s.ID_TacGia == tg.ID_TacGia && s.ID_TheLoai == tl.ID_TheLoai)
                           select new
                           {
                               sach = new Sach(s.ID_Sach, s.TenSach, s.GiaTien, s.SoLuong, s.UrlImg, s.NgayNhap),
                               tacGia = new TacGia(tg.ID_TacGia, tg.TenTacGia, tg.QuocGia),
                               theLoai = new TheLoai(tl.ID_TheLoai, tl.TenTheLoai)
                           };

            foreach (var item in dataSach)
            {
                InfoBook infoBook = new InfoBook(item.sach, item.tacGia, item.theLoai);
                lstSach.AddLast(infoBook);
            }
            return lstSach;
        }

        // GET View Create
        public IActionResult Create()
        {
            var theLoais = from tl in _db.TheLoais
                          select tl;

            foreach(var item in theLoais)
            {
                TheLoaiSelectList.Add(new SelectListItem { Text = item.TenTheLoai, Value = item.ID_TheLoai.ToString() });
            }

            InfoBook infoBook = new InfoBook();
            infoBook.TheLoaiSelectList = TheLoaiSelectList;

            return View(infoBook);
        }

        // POST Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(InfoBook infoBook)
        {
            int idTacGia;
            // Kiểm tra tác giả tồn tại trong csld chưa
            // True thì thêm sách mới
            // False thì thêm tác giả mới vào csdl sau đó thêm thông tin sách
            bool isTg = checkTacGia(infoBook.Sach.TacGia.TenTacGia, infoBook.Sach.TacGia.QuocGia);
            if (isTg)
            {
                idTacGia = selectIdTacGia(infoBook.Sach.TacGia.TenTacGia, infoBook.Sach.TacGia.QuocGia);
                Sach sach = new Sach();
                sach.TenSach = infoBook.Sach.TenSach.ToUpper();
                sach.GiaTien = infoBook.Sach.GiaTien;
                sach.SoLuong = infoBook.Sach.SoLuong;
                sach.UrlImg = infoBook.Sach.UrlImg;
                sach.NgayNhap = DateTime.Now;
                sach.ID_TacGia = idTacGia;
                sach.ID_TheLoai = infoBook.Sach.TheLoai.ID_TheLoai;
                // Thêm sách mới
                try
                {
                    await _db.Saches.AddAsync(sach);
                    await _db.SaveChangesAsync();
                    TempData["success"] = "Thêm sách mới thành công";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.InnerException.Message;
                    return RedirectToAction("Index");
                }
            }
            else
            {
                bool isAddTacGia = addTacGia(infoBook.Sach.TacGia);
                if (isAddTacGia)
                {
                    idTacGia = selectIdTacGia(infoBook.Sach.TacGia.TenTacGia, infoBook.Sach.TacGia.QuocGia);
                    Sach sach = new Sach();
                    sach.TenSach = infoBook.Sach.TenSach.ToUpper();
                    sach.GiaTien = infoBook.Sach.GiaTien;
                    sach.SoLuong = infoBook.Sach.SoLuong;
                    sach.UrlImg = infoBook.Sach.UrlImg;
                    sach.NgayNhap = DateTime.Now;
                    sach.ID_TacGia = idTacGia;
                    sach.ID_TheLoai = infoBook.Sach.TheLoai.ID_TheLoai;
                    // Thêm sách mới
                    try
                    {
                        await _db.Saches.AddAsync(sach);
                        await _db.SaveChangesAsync();
                        TempData["success"] = "Thêm sách mới thành công";
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        TempData["error"] = ex.InnerException.Message;
                        return RedirectToAction("Index");
                    }
                }
            }

            return View(infoBook);
        }

        // Method tìm kiêm Id tác giả để thêm sách mới
        public int selectIdTacGia(string tenTacGia, string quocGia)
        {
            var tacGia = from tg in _db.TacGias
                         where tg.TenTacGia == tenTacGia && tg.QuocGia == quocGia
                         select tg.ID_TacGia;
            foreach(var tg in tacGia)
            {
                return tg;
            }
            return 0;
        }

        // Method kiểm tra tác giả có trong csdl hay chưa
        public bool checkTacGia(string tenTacGia, string quocGia)
        {
            var tacgia = from tg in _db.TacGias
                         where tg.TenTacGia.ToUpper() == tenTacGia.ToUpper() && tg.QuocGia.ToUpper() == quocGia.ToUpper()
                         select tg;
            if(tacgia.Count() > 0)
            {
                return true;
            }
            return false;
        }

        // Method thêm dữ liệu vào bảng tác giả trong trường hợp tác giả chưa tồn tại trong csdl
        public bool addTacGia(TacGia obj)
        {
            if (obj == null)
            {
                return false;
            } else
            {
                _db.Add(obj);
                if(_db.SaveChanges() > 0)
                {
                    return true;
                }
            }
            return false;
        }
        
        // Get View edit
        public IActionResult ViewEdit(int? id)
        {
            var dataSach = from s in _db.Saches
                           from tg in _db.TacGias
                           from tl in _db.TheLoais
                           where (s.ID_TacGia == tg.ID_TacGia && s.ID_TheLoai == tl.ID_TheLoai && s.ID_Sach == id)
                           select new
                           {
                               sach = new Sach(s.ID_Sach, s.TenSach, s.GiaTien, s.SoLuong, s.UrlImg, s.NgayNhap),
                               tacGia = new TacGia(tg.ID_TacGia, tg.TenTacGia, tg.QuocGia),
                               theLoai = new TheLoai(tl.ID_TheLoai, tl.TenTheLoai)
                           };

            var theLoais = from tl in _db.TheLoais
                           select tl;
            foreach (var item in theLoais)
            {
                TheLoaiSelectList.Add(new SelectListItem { Text = item.TenTheLoai, Value = item.ID_TheLoai.ToString() });
            }

            InfoBook info = new InfoBook();
            info.TheLoaiSelectList = TheLoaiSelectList;

            foreach (var item in dataSach)
            {
                info.Sach = item.sach;
                info.TacGia = item.tacGia;
                info.TheLoai = item.theLoai;
            }

            return View(info);
        }
        
        // Post Edit
        [HttpPost]

QuanLyThuVien/Views/Shared/_Layout.cshtml
@using QuanLyThuVien.Controllers;

@{
    var data = LoginController.layout;
}

@* Hàm kiểm tra và add class active khi click sidebar-link *@
@* @{
    string isActive(string controller, string action)
    {
        var result = Context.Request.Path == $"/{controller}" ? "active"
                    : Context.Request.Path == $"/{controller}/{action}" ? "active"
                    : "";
        return result;
    }
} *@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuanLyThuVien</title>
    <link rel="stylesheet" href="~/css/bootswatch_flatly.css" />
    <link rel="stylesheet" href="~/css/Home.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <input type="checkbox" id="nav-toggle">
    <div class="sidebar" target="_sidebar">
        <div class="sidebar-brand">
            <a asp-controller="Home" asp-action="Index">
                <h2 class="lv2">
                    <img src="~/Images/logo/logo-svg.webp" class="logo" />
                    <span>EAUT Libary</span>
                </h2>
            </a>
        </div>
        <div class="sidebar-menu">
            <ul>
                <li>
                    <a asp-controller="Home" asp-action="Index" id="Home" title="Dasboard" class="sidebar-link">
                        <span>
                            <i class="bi bi-house"></i>
                        </span>
                        <span>Dasboard</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="QuanTriHeThong" asp-action="Index" id="QuanTriHeThong" title="Quản trị hệ thống" class="sidebar-link">
                        <span>
                            <i class="bi bi-server"></i>
                        </span>
                        <span>Quản trị hệ thống</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="QuanLySach" asp-action="Index" id="QuanLySach" title="Quản lý kho sách" class="sidebar-link">
                        <span>
                            <i class="bi bi-book"></i>
                        </span>
                        <span>Quản lý kho sách</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="QuanLyDocGia" asp-action="Index" id="QuanLyDocGia" title="Quản lý độc giả" class="sidebar-link">
                        <span>
                            <i class="bi bi-file-person"></i>
                        </span>
                        <span>Quản lý độc giả</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="QuanLyMuonTraSach" asp-action="ViewSachMuon" id="QuanLyMuonTraSach" title="Quản lý mượn trả sách" class="sidebar-link">
                        <span>
                            <i class="bi bi-file-earmark-ruled"></i>
                        </span>
                        <span>Quản lý mượn trả sách</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="BaoCaoThongKe" asp-action="Index" id="BaoCaoThongKe" title="Báo cáo thống kê" class="sidebar-link">
                        <span>
                            <i class="bi bi-file-earmark-bar-graph"></i>
                        </span>
                        <span>Báo cáo thống kê</span>
                    </a>
                </li>

                @* <li>
                    <a asp-controller="BaoCaoThongKe" asp-action="Index" id="BaoCaoThongKe" title="Báo cáo thống kê" class="sidebar-link @isActive("BaoCaoThongKe", ViewContext.RouteData.Values["action"].ToString())">
                        <span>
                            <i class="bi bi-file-earmark-bar-graph"></i>
                        </span>
                        <span>Báo cáo thống kê</span>
                    </a>
                </li> *@

                <li>
                    <a asp-controller="Login" asp-action="Index" title="Thoát">
                        <span>
                            <i class="bi bi-box-arrow-left"></i>
                        </span>
                        <span>Thoát</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-content">
        <header>
            <h2 class="lv2">
                <label for="nav-toggle">
                    <span>
                        <i class="bi bi-list"></i>
                    </span>
                </label>
            </h2>
            <div class="search-wrapper">
                <span>
                    <i class="bi bi-search"></i>
                </span>
                <input type="search" placeholder="Search here" />
            </div>

            <div class="user-wrapper">
                <img src="~/Images/avatar/admin.png" alt="" width="30px" height="30px">
                <div>
                    <h4 class="lv4">@data.TenDangNhap</h4>
                    <small>@data.VaiTro</small>
                </div>
            </div>
        </header>
        @RenderBody()
        <partial name="_Notifications">
        @section Scripts {
            @{
                <partial name="_ValidationScriptsPartial" />
            }
        }
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

QuanLyThuVien/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuanLyThuVien</title>
    <link rel="stylesheet" href="~/css/bootswatch_flatly.css" />
    <link rel="stylesheet" href="~/css/Login.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <div class="bg-primary" style="height:100vh;">
        <main role="main" class="pb-3 main h-100">
            <partial name="_Notifications">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

QuanLyThuVien/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

@if (TempData["message"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.info('@TempData["message"]');
    </script>
}