QuanLyThuVien/Controllers/QuanLyDocGiaController.cs
using Microsoft.AspNetCore.Mvc;
using QuanLyThuVien.Data;
using QuanLyThuVien.Models;

namespace QuanLyThuVien.Controllers
{
    public class QuanLyDocGiaController : Controller
    {
        private readonly ApplicationDbContext _db;
        public QuanLyDocGiaController(ApplicationDbContext db)
        {
            _db = db;
        }


        // GET View Index
        public IActionResult Index()
        {
            IQueryable<DocGia> lstDG = getDataDocGia();
            if(lstDG.Count() <= 0)
            {
                TempData["message"] = "Dữ liệu trống";
            }
            return View(lstDG);
        }

        // Phương thức get data DocGia
        public IQueryable<DocGia> getDataDocGia()
        {
            var obj = from dg in _db.DocGias
                      select dg;
            return obj;
        }

        // GET view Create
        public IActionResult Create()
        {
            return View();
        }

        // POST create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePost(DocGia docGia)
        {
            try
            {
                if (docGia == null) { return BadRequest(); }
                bool isAddTaiKhoan = addTaiKhoanDocGia(docGia.Email);
                bool isAddTheThuVien = addTheThuVien(docGia.SoCCCD);

                if (isAddTaiKhoan && isAddTheThuVien)
                {
                    try
                    {
                        int maTK = getMaTK(docGia.Email);
                        int maThe = getMaThe(docGia.SoCCCD);
                        if (maTK != 0 && maThe != 0)
                        {
                            DocGia dg = docGia;
                            dg.ID_TaiKhoan = maTK;
                            dg.ID_The = maThe;

                            await _db.DocGias.AddAsync(dg);
                            await _db.SaveChangesAsync();

                            TempData["success"] = "Thêm mới độc giả thành công";
                            return RedirectToAction("Index");
                        }
                    } catch(Exception ex)
                    {
                        removeTaiKhoan(docGia.Email);
                        removeTheThuVien(docGia.SoCCCD);

                        TempData["error"] = ex.InnerException.Message;
                        return RedirectToAction("Index");
                    }
                }
            } catch(Exception ex)
            {
                TempData["error"] = ex.InnerException.Message;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        // GET view Edit
        public IActionResult Edit(int? id)
        {
            var obj = from dg in _db.DocGias
                      where dg.ID_DocGia == id
                      select dg;

            foreach (var docgia in obj)
            {
                return View(docgia);
            }

            return NotFound();
        }

        // Post Edit
        public async Task<IActionResult> EditPost(DocGia obj)
        {
            try
            {
                _db.DocGias.Update(obj);
                await _db.SaveChangesAsync();
                TempData["success"] = "Sửa thông tin độc giả thành công";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.InnerException.Message;
                return RedirectToAction("Index");
            }
        }

        // Get view delete
        public IActionResult Delete(int? id)
        {
            var obj = _db.DocGias.Find(id);
            if (obj == null) return NotFound();
            return View(obj);
        }

        // Post Delete
        public async Task<IActionResult> DeletePost(int? idDocGia)
        {
            var obj = _db.DocGias.Find(idDocGia);
            if (obj == null) return NotFound();
            try
            {
                _db.DocGias.Remove(obj);
                await _db.SaveChangesAsync();

                /*
                    Khi xóa độc giả thì sẽ xóa luôn cả thông tin tài khoản 
                    và thẻ thư viện của độc giả đó.
                 */
                removeTaiKhoan(obj.Email);
                removeTheThuVien(obj.SoCCCD);

                TempData["success"] = "Xóa độc giả thành công";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.InnerException.Message;
                return RedirectToAction("Index");
            }
        }

        /*
            Phương thức tạo tài khoản khi thêm mới độc giả
            Tên tài khoản = email
            Mật khẩu = 123456;
         */
        public bool addTaiKhoanDocGia(string email)
        {
            if(email == null) { return false; }
            TaiKhoan tk = new TaiKhoan();
            tk.TenDangNhap = email;
            tk.MatKhau = "123456";
            tk.VaiTro = "Độc giả";

            _db.TaiKhoans.AddAsync(tk);
            if(_db.SaveChanges() > 0)
            {
                return true;
            }
            return false;
        }

        // Phương thức lấy mã tài khoản độc giả
        public int getMaTK(string tentk)
        {
            var maTK = from tk in _db.TaiKhoans
                       where tk.TenDangNhap == tentk
                       select tk.ID_TaiKhoan;
            foreach(var item in maTK)
            {
                return item;
            }

            return 0;
        }

        /*
            Phương thức tạo thẻ thư viện khi thêm mới độc giả
            NgayDB = DateTime.Now;
            Thời hạn của 1 thẻ là 3 năm kể từ ngày tạo
            Lưu thông tin ghi chú = số cccd
         */
        public bool addTheThuVien(string SoCCCD)
        {
            TheThuVien the = new TheThuVien();
            the.NgayBD = DateTime.Now;
            the.NgayHetHan = new DateTime(the.NgayBD.Year + 3, the.NgayBD.Month, the.NgayBD.Day);
            the.GhiChu = SoCCCD;

            _db.TheThuViens.AddAsync(the);
            if (_db.SaveChanges() > 0) return true;
            return false;
        }

        // Phương thức lấy mã thẻ thư viện
        public int getMaThe(string soCCCD)
        {
            var maThes = from th in _db.TheThuViens
                         where th.GhiChu == soCCCD
                         select th.ID_The;
            foreach(var item in maThes)
            {
                return item;
            }

            return 0;
        }

        // Phương thức xóa thông tin tài khoản nếu thêm độc giả xảy ra lỗi
        public void removeTaiKhoan(string email)
        {
            var obj = from tk in _db.TaiKhoans
                      where tk.TenDangNhap == email
                      select tk;
            TaiKhoan taiKhoan = new TaiKhoan();
            foreach(var i in obj)
            {
                taiKhoan = i;
            }
            _db.Remove(taiKhoan);
            _db.SaveChanges();
        }

        // Phương thức xóa thông tin thẻ thư viện nếu thêm độc giả xảy ra lỗi
        public void removeTheThuVien(string soCCCD)
        {
            var obj = from t in _db.TheThuViens
                      where t.GhiChu == soCCCD
                      select t;

            TheThuVien the = new TheThuVien();
            foreach (var i in obj)
            {
                the = i;
            }
            _db.Remove(the);
            _db.SaveChanges();
        }
    }
}

QuanLyThuVien/Views/QuanLyDocGia/Create.cshtml
@model DocGia
@{
    ViewData["Title"] = "Create";
}

<main>
    <form method="post" asp-controller="QuanLyDocGia" asp-action="CreatePost" style="width: 50%;">
        <fieldset>
            <legend>Thêm độc giả mới</legend>
            <div class="form-group">
                <label asp-for="@Model.TenDocGia" class="form-label mt-4">Tên độc giả</label>
                <input asp-for="@Model.TenDocGia" type="text" class="form-control" required id="TenDocGia" placeholder="Nhập tên độc giả">
            </div>
            <div class="form-group">
                <label asp-for="@Model.SoCCCD" class="form-label mt-4">Số căn cước công dân</label>
                <input asp-for="@Model.SoCCCD" class="form-control" type="text" required id="CCCD" placeholder="Nhập số căn cước công dân">
            </div>
            <div class="form-group">
                <label asp-for="@Model.GioiTinh" class="form-label mt-4">Giới tính</label>
                <input asp-for="@Model.GioiTinh" type="text" class="form-control" required id="GioiTinh" placeholder="Nhập giới tính">
            </div>
            <div class="form-group">
                <label asp-for="@Model.NgaySinh" class="form-label mt-4">Ngày sinh</label>
                <input asp-for="@Model.NgaySinh" type="date" class="form-control" required id="NgaySinh">
            </div>
            <div class="form-group">
                <label asp-for="@Model.DiaChi" class="form-label mt-4">Địa chỉ</label>
                <input asp-for="@Model.DiaChi" type="text" class="form-control" required id="DiaChi" placeholder="Nhập địa chỉ">
            </div>
            <div class="form-group">
                <label asp-for="@Model.SDT" class="form-label mt-4">Số điện thoại</label>
                <input asp-for="@Model.SDT" type="text" class="form-control" required id="SDT" placeholder="Nhập số điện thoại">
            </div>
            <div class="form-group">
                <label asp-for="@Model.Email" class="form-label mt-4">Email</label>
                <input asp-for="@Model.Email" type="email" class="form-control" required id="Email" placeholder="Nhập email">
            </div>
            <div class="mt-3">
                <a asp-controller="QuanLyDocGia" asp-action="Index" class="btn btn-outline-primary" style="margin-right: 4px">Quay lại</a>
                <button type="submit" class="btn btn-success">
                    <i class="bi bi-plus-circle"></i>&nbsp; Create
                </button>
            </div>
        </fieldset>
    </form>
</main>

QuanLyThuVien/Views/QuanLyDocGia/Delete.cshtml
@model DocGia
@{
    ViewData["Title"] = "Delete";
}

<main>
    <form method="post" asp-controller="QuanLyDocGia" asp-action="DeletePost" id="form-delete" style="width: 50%;">
        <fieldset>
            <legend>Xóa độc giả</legend>
            <div class="form-group">
                <input asp-for="@Model.ID_DocGia" type="text" name="idDocGia" class="form-control" id="IdDocGia" hidden>
            </div>
            <div class="form-group">
                <label asp-for="@Model.TenDocGia" class="form-label mt-4">Tên độc giả</label>
                <input asp-for="@Model.TenDocGia" type="text" class="form-control" id="TenDocGia" disabled="">
            </div>
            <div class="form-group">
                <label asp-for="@Model.SoCCCD" class="form-label mt-4">Số căn cước công dân</label>
                <input asp-for="@Model.SoCCCD" class="form-control" type="text" id="CCCD" disabled="">
            </div>
            <div class="form-group">
                <label asp-for="@Model.GioiTinh" class="form-label mt-4">Giới tính</label>
                <input asp-for="@Model.GioiTinh" type="text" class="form-control" id="GioiTinh" disabled="">
            </div>
            <div class="form-group">
                <label asp-for="@Model.NgaySinh" class="form-label mt-4">Ngày sinh</label>
                <input asp-for="@Model.NgaySinh" type="date" class="form-control" id="NgaySinh" disabled="">
            </div>
            <div class="form-group">
                <label asp-for="@Model.DiaChi" class="form-label mt-4">Địa chỉ</label>
                <input asp-for="@Model.DiaChi" type="text" class="form-control" id="DiaChi" disabled>
            </div>
            <div class="form-group">
                <label asp-for="@Model.SDT" class="form-label mt-4">Số điện thoại</label>
                <input asp-for="@Model.SDT" type="text" class="form-control" id="SDT" disabled="">
            </div>
            <div class="form-group">
                <label asp-for="@Model.Email" class="form-label mt-4">Email</label>
                <input asp-for="@Model.Email" type="email" class="form-control" id="Email" disabled="">
            </div>
            <div class="mt-3">
                <a asp-controller="QuanLyDocGia" asp-action="Index" class="btn btn-outline-primary" style="margin-right: 4px">Quay lại</a>
                <button type="button" onclick="handleSubmitForm()" class="btn btn-outline-danger">Delete</button>
            </div>
        </fieldset>
    </form>

    <div class="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Thông báo</h5>
                    <button type="button" class="btn-close" value="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Bạn có chắc chắn muốn xóa?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" value="submit" class="btn btn-danger">Yes</button>
                    <button type="button" class="btn btn-secondary" value="close" data-bs-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
</main>

QuanLyThuVien/Views/QuanLyDocGia/Edit.cshtml
@model DocGia
@{
    ViewData["Title"] = "Edit";
}
<main>
    <form method="post" asp-controller="QuanLyDocGia" asp-action="EditPost" style="width: 50%;">
        <fieldset>
            <legend>Sửa thông tin độc giả</legend>
            <div class="form-group">
                <input asp-for="@Model.ID_DocGia" type="text" class="form-control" required id="IdDocGia" hidden>
            </div>
            <div class="form-group">
                <input asp-for="@Model.ID_TaiKhoan" type="text" class="form-control" required id="IdTaiKhoan" hidden>
            </div>
            <div class="form-group">
                <input asp-for="@Model.ID_The" type="text" class="form-control" required id="IdThe" hidden>
            </div>
            <div class="form-group">
                <label asp-for="@Model.TenDocGia" class="form-label mt-4">Tên độc giả</label>
                <input asp-for="@Model.TenDocGia" type="text" class="form-control" required id="TenDocGia" placeholder="Nhập tên độc giả">
            </div>
            <div class="form-group">
                <label asp-for="@Model.SoCCCD" class="form-label mt-4">Số căn cước công dân</label>
                <input asp-for="@Model.SoCCCD" class="form-control" type="text" required id="CCCD" placeholder="Nhập số căn cước công dân">
            </div>
            <div class="form-group">
                <label asp-for="@Model.GioiTinh" class="form-label mt-4">Giới tính</label>
                <input asp-for="@Model.GioiTinh" type="text" class="form-control" required id="GioiTinh" placeholder="Nhập giới tính">
            </div>
            <div class="form-group">
                <label asp-for="@Model.NgaySinh" class="form-label mt-4">Ngày sinh</label>
                <input asp-for="@Model.NgaySinh" type="date" class="form-control" required id="NgaySinh">
            </div>
            <div class="form-group">
                <label asp-for="@Model.DiaChi" class="form-label mt-4">Địa chỉ</label>
                <input asp-for="@Model.DiaChi" type="text" class="form-control" required id="DiaChi" placeholder="Nhập địa chỉ">
            </div>
            <div class="form-group">
                <label asp-for="@Model.SDT" class="form-label mt-4">Số điện thoại</label>
                <input asp-for="@Model.SDT" type="text" class="form-control" required id="SDT" placeholder="Nhập số điện thoại">
            </div>
            <div class="form-group">
                <label asp-for="@Model.Email" class="form-label mt-4">Email</label>
                <input asp-for="@Model.Email" type="email" class="form-control" required id="Email" placeholder="Nhập email">
            </div>
            <div class="mt-3">
                <a asp-controller="QuanLyDocGia" asp-action="Index" class="btn btn-outline-primary" style="margin-right: 4px">Quay lại</a>
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </fieldset>
    </form>
</main>

QuanLyThuVien/Views/QuanLyDocGia/Index.cshtml
@model IQueryable<DocGia>
@{
    ViewData["Title"] = "Index";
}

<main>
    <h2 class="lv2">Danh sách độc giả</h2>
    <div class="text-start" style="margin: 12px 0;">
        <a asp-controller="QuanLyDocGia" asp-action="Create" class="btn btn-outline-primary">
            <i class="bi bi-plus-circle"></i>&nbsp; Tạo mới
        </a>
    </div>
    <table class="table table-hover">
        <thead>
            <tr class="table-primary">
                <th scope="col">Id</th>
                <th scope="col">Tên độc giả</th>
                <th scope="col">Giới tính</th>
                <th scope="col">Ngày sinh</th>
                <th scope="col">Địa chỉ</th>
                <th scope="col">Số điện thoại</th>
                <th scope="col">Email</th>
                <th scope="col">Hành động</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.ID_DocGia</th>
                    <td>@item.TenDocGia</td>
                    <td>@item.GioiTinh</td>
                    <td>@item.NgaySinh</td>
                    <td>@item.DiaChi</td>
                    <td>@item.SDT</td>
                    <td>@item.Email</td>
                    <td>
                        <a asp-controller="QuanLyDocGia" asp-action="Edit" asp-route-id="@item.ID_DocGia" class="btn btn-outline-primary" title="Sửa">
                            <i class="bi bi-gear"></i>
                        </a>
                        <a asp-controller="QuanLyDocGia" asp-action="Delete" asp-route-id="@item.ID_DocGia" class="btn btn-outline-danger" style="margin: 0 8px;" title="Xóa">
                            <i class="bi bi-trash3"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</main>